### ISSUE TITLE
Система сборки

### ISSUE THREAD

**Issue by kazeevn** [kazeevn/Canecycle-of-Caerbannog#1]
Придумать, как мы это будем собирать (make, cmake?), поместить тесты в отдельную папку.

**Comment by sklef** [comment]
http://stackoverflow.com/questions/25789644/makefile-vs-cmake
Похоже CMake будет куда полезнее чем Make, вопрос в том насколько эти фичи нам нужны и есть ли у кого опыт работы с CMake

**Comment by sklef** [comment]
И в нагрузку на тему системы сборки и тестов. Кажется, что это будет очень полезной фичей https://travis-ci.org/getting_started По крайней мере sklearn при коммите автоматически собирается в этой штуке
